In [1]:
import torch

In [11]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
x.reshape((3, 4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
torch.randn((2, 3))

tensor([[ 1.3373,  0.6776, -0.6934],
        [-0.6291, -0.7140,  0.3076]])

In [17]:
torch.rand((2, 3))

tensor([[0.4926, 0.0912, 0.5515],
        [0.1375, 0.9011, 0.0134]])

In [18]:
torch.tensor([[2,1,3,4],[1,2,3,4],[1,1,1,1]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [1, 1, 1, 1]])

In [20]:
x = torch.Tensor([[2,1,3,4],[1,2,3,4],[1,1,1,1]])

In [24]:
x[-1],x[0:2]

(tensor([1., 1., 1., 1.]),
 tensor([[2., 1., 3., 4.],
         [1., 2., 3., 4.]]))

In [25]:
x[:2,:]

tensor([[2., 1., 3., 4.],
        [1., 2., 3., 4.]])

In [26]:
torch.exp(x)

tensor([[ 7.3891,  2.7183, 20.0855, 54.5982],
        [ 2.7183,  7.3891, 20.0855, 54.5982],
        [ 2.7183,  2.7183,  2.7183,  2.7183]])

In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [28]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[12., 15., 18., 21.]]),
 tensor([[ 6.],
         [22.],
         [38.]]))

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [33]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [34]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [37]:
Z = torch.zeros_like(Y)
print(f'id(Z):{id(Z)}')
Z[:] = X+Y
print(f'id(Z):{id(Z)}')

id(Z):140606661226512
id(Z):140606661226512


In [38]:
before = id(Y)
Y += X
id(Y) == before

True

In [40]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [41]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [42]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x,y,x==y,x<y,x>y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [44]:
x = torch.arange(12,dtype=torch.float32)
y = torch.arange(5,dtype=torch.float32).reshape((5,-1))
print(x,y)
x+y

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]) tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
        [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
        [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]])