In [1]:
import torch

In [2]:
x, y = torch.tensor(3.0), torch.tensor(2.0)
x, y

(tensor(3.), tensor(2.))

In [3]:
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [5]:
x[2]

tensor(2)

In [6]:
len(x)

3

In [7]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [9]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [13]:
A,B,A * B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]))

In [15]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [16]:
a*X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [17]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [18]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [21]:
A.shape, A.sum(0,keepdim=True), A.sum(0).shape

(torch.Size([2, 3]), tensor([[3., 5., 7.]]), torch.Size([3]))

In [24]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [25]:
A.mean(),A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [26]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [27]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [29]:
A,A / sum_A

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [32]:
B = torch.arange(18, dtype=torch.float32).reshape(3, -1)
B, B.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  8., 10., 12., 14., 16.],
         [18., 21., 24., 27., 30., 33.]]))

In [34]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [36]:
torch.dot(x, y) == (x*y).sum()

tensor(True)

In [39]:
A.shape, x.shape, torch.mv(A, x), A@x
# matrix @ vector 
# a^T * x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [50]:
x.unsqueeze(1)

tensor([[0.],
        [1.],
        [2.]])

In [51]:
A,x,(A@x).shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 torch.Size([2]))

In [52]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [53]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [54]:
torch.abs(u).sum()

tensor(7.)

In [57]:
torch.ones((4, 9)),torch.norm(torch.ones((4, 9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))

In [58]:
A = torch.arange(12,dtype=torch.float32).reshape(3,4)
A == A.T.T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [59]:
B = torch.arange(12,dtype=torch.float32).reshape(3,4)
A.T+B.T == (A+B).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])