# back propagtion
main stream use this
# forward propagation
ref from: https://arxiv.org/pdf/1607.07892.pdf

In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True)
x.grad

In [6]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad == 4 * x

tensor([True, True, True, True])

In [9]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [11]:
x.grad = None
y = x*x
y.sum().backward()
x,x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), tensor([0., 2., 4., 6.]))

In [13]:
x.grad = None
y = x*x
u = y.detach()

z = u * x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [14]:
x.grad = None
y = x*x

z = y * x
z.sum().backward()
x.grad

tensor([ 0.,  3., 12., 27.])