In [1]:
import torch
from torch import nn


In [2]:
net = nn.Sequential(
    nn.LazyLinear(8),
    nn.ReLU(),
    nn.LazyLinear(1)
)
x = torch.rand((2, 4))
net(x).shape

/Users/tangyun/opt/miniconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

In [4]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.0673,  0.1761,  0.3235,  0.2232,  0.2003,  0.2954, -0.1700,  0.2133]])),
             ('bias', tensor([-0.3205]))])

In [6]:
type(net[2].bias),net[2].bias.data

(torch.nn.parameter.Parameter, tensor([-0.3205]))

In [8]:
net[2].weight.grad == None

True

In [10]:
[(name, param.shape, param.numel()) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4]), 32),
 ('0.bias', torch.Size([8]), 8),
 ('2.weight', torch.Size([1, 8]), 8),
 ('2.bias', torch.Size([1]), 1)]

In [18]:
shared = nn.LazyLinear(8)
net = nn.Sequential(
    nn.LazyLinear(8),
    nn.ReLU(),
    shared,
    nn.ReLU(),
    shared,
    nn.ReLU(),
    nn.LazyLinear(1)
)
net(x)
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0,0]=100
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])
