In [2]:
import torch
from torch import nn

In [3]:
net = nn.Sequential(
    nn.LazyLinear(8),
    nn.ReLU(),
    nn.LazyLinear(1)
)
x = torch.rand(2,4)
net(x).shape

/Users/tangyun/opt/miniconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

In [5]:
print(net[0].weight.data[0],net[0].bias.data[0])
def init_normal(module):
    if type(module) == nn.Linear:
        nn.init.normal_(module.weight, mean=0,std=0.01)
        nn.init.zeros_ (module.bias)
net.apply(init_normal)
print(net[0].weight.data[0],net[0].bias.data[0])

tensor([ 0.1654, -0.1621, -0.4912,  0.1595]) tensor(-0.4735)
tensor([-0.0069, -0.0107, -0.0108, -0.0008]) tensor(0.)


In [7]:
def init_xavier(module):
    if type(module) == nn.Linear:
        nn.init.xavier_uniform_(module.weight)
def init_42(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 42)
net[0].apply(init_xavier)
net[2].apply(init_42)

net[0].weight.data[0],net[2].weight.data

(tensor([0.4013, 0.4156, 0.1730, 0.3063]),
 tensor([[42., 42., 42., 42., 42., 42., 42., 42.]]))

In [10]:
def my_init(module):
    if type(module) == nn.Linear:
        print("Init", *[(name, param.shape)
              for name, param in module.named_parameters()][0])
        nn.init.uniform_(module.weight, -10, 10)
        module.weight.data *= module.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
Init weight torch.Size([1, 8])


tensor([[ 5.2848,  5.2347,  6.2336, -9.4432],
        [-8.4274,  8.1974,  0.0000, -6.7465]], grad_fn=<SliceBackward0>)

In [11]:
net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
net[0].weight.data[0]

tensor([42.0000,  6.2347,  7.2336, -8.4432])