In [2]:
import torch
from torch import nn
import torch.nn.functional as F

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x-x.mean()

In [4]:
layer = CenteredLayer()
layer(torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

y = net(torch.rand(4, 8))
y.mean()

/Users/tangyun/opt/miniconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor(0., grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.4810,  0.0735, -0.4222],
        [ 0.2831, -1.0036,  0.1715],
        [ 0.2326, -2.6600,  0.7482],
        [-0.2697,  0.5160, -1.6946],
        [-1.3695, -0.1996,  1.9503]], requires_grad=True)

In [8]:
linear(torch.randn(2,5))

tensor([[0.0000, 1.4725, 0.0000],
        [0.0000, 7.7725, 0.0000]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2,64))

tensor([[4.5750],
        [9.9797]])