In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
x = torch.arange(4)
torch.save(x,'x-file')

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

In [6]:
net = MLP()
x = torch.randn(2,20)
y = net(x)
y

/Users/tangyun/opt/miniconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor([[-0.2269,  0.1736,  0.4085,  0.2879,  0.6492,  0.0276, -0.0963, -0.1678,
         -0.4640,  0.1742],
        [-0.0311,  0.6629,  0.3142,  0.3067,  0.0251, -0.1035,  0.1801, -0.2677,
         -0.0672,  0.5237]], grad_fn=<AddmmBackward0>)

In [9]:
torch.save(net.state_dict(),'mlp.params')

In [10]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [12]:
y_clone = clone(x)
y_clone == y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])