In [1]:
import torch
from torch import nn

In [2]:
def pool2d(x, pool_size, mode='max'):
    p_h, p_w = pool_size
    y = torch.zeros(x.shape[0] - p_h + 1, x.shape[1] - p_w + 1)
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            if mode == 'max':
                y[i,j] = x[i:i+p_h, j:j+p_w].max()
            elif mode == 'avg':
                y[i,j] = x[i:i+p_h, j:j+p_w].mean()
    return y

In [6]:
x = torch.arange(9,dtype=torch.float32).view(3,3)
pool2d(x,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [7]:
pool2d(x,(2,2),'avg')

tensor([[2., 3.],
        [5., 6.]])

In [8]:
x = torch.arange(16,dtype=torch.float32).view(1,1,4,4)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [9]:
pool2d = nn.MaxPool2d(3)
pool2d(x)

tensor([[[[10.]]]])

In [10]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(x)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [11]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(x)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [20]:
x = torch.arange(16).float().reshape(1,1,4,4)
x = torch.cat((x,x+1),dim=1)
x,x.shape

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],
 
          [[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10., 11., 12.],
           [13., 14., 15., 16.]]]]),
 torch.Size([1, 2, 4, 4]))

In [19]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(x).shape

torch.Size([1, 2, 2, 2])